#!/usr/bin/env python3
"""Pull the drawings and price bands the site uses out of Manager's ingredient
file (itself generated from the Copius data). Run after a Copius data change,
giving that file's path:

    python3 tools/extract-art.py <manager repo>/data/ingredients.js
"""
import json, re, sys, pathlib
if len(sys.argv) < 2: sys.exit("usage: extract-art.py <path to Manager's data/ingredients.js>")
SRC = pathlib.Path(sys.argv[1])
IDS = ["sea-bass","asparagus","butter","lemon","rice","porcini","parmesan","shallot",
       "salmon","potato","scallop","truffle","lobster","artichoke","strawberry",
       "leek","cod","egg","basil","carrot","onion","garlic","thyme"]
s = SRC.read_text(encoding="utf-8")
rows = json.loads(s.split("=", 1)[1].strip().rstrip(";"))
by = {r["id"]: r for r in rows}
missing = [i for i in IDS if i not in by]
if missing: sys.exit("missing ids: " + ", ".join(missing))
art = {i: {"fr": by[i]["fr"], "en": by[i]["en"], "lo": by[i]["lo"], "hi": by[i]["hi"],
           "unit": by[i]["unit"], "season": by[i].get("season") or [], "svg": by[i]["svg"]} for i in IDS}
out = pathlib.Path(__file__).resolve().parent.parent / "js" / "art.js"
out.write_text("/* Drawings and price bands from the Copius atlas, for the site.\n"
               "   Generated by tools/extract-art.py — do not edit. */\n"
               "window.NOKIME_ART=" + json.dumps(art, ensure_ascii=False, separators=(",", ":")) + ";\n",
               encoding="utf-8")
print(f"{len(art)} drawings → {out.relative_to(out.parent.parent)} ({out.stat().st_size//1024} KB)")
