#!/usr/bin/env python3
"""Pull the drawings and price bands the site uses out of Manager's ingredient
file (itself generated from the Copius data). Run after a Copius data change,
giving that file's path:

    python3 tools/extract-art.py <manager repo>/data/ingredients.js
"""
import json, re, sys, pathlib
if len(sys.argv) < 2: sys.exit("usage: extract-art.py <path to Manager's data/ingredients.js>")
SRC = pathlib.Path(sys.argv[1])
IDS = ["sea-bass","asparagus","butter","lemon","rice","porcini","parmesan","shallot",
       "salmon","potato","scallop","truffle","lobster","artichoke","strawberry",
       "leek","cod","egg","basil","carrot","onion","garlic","thyme"]
s = SRC.read_text(encoding="utf-8")
rows = json.loads(s.split("=", 1)[1].strip().rstrip(";"))
by = {r["id"]: r for r in rows}
missing = [i for i in IDS if i not in by]
if missing: sys.exit("missing ids: " + ", ".join(missing))
art = {i: {"fr": by[i]["fr"], "en": by[i]["en"], "lo": by[i]["lo"], "hi": by[i]["hi"],
           "unit": by[i]["unit"], "season": by[i].get("season") or [], "svg": by[i]["svg"]} for i in IDS}

# The house's own drawings, in the atlas's hand: what Manager and Jobs are about.
EXTRA = {
    "icon-balance": {"fr": "Balance", "en": "Scale", "svg": '<path class="f2 sf" d="M45 36h6v50h-6z"/><ellipse class="f3 sf" cx="48" cy="86" rx="18" ry="3.5"/><path class="s" d="M14 41L82 31"/><path class="s" d="M14 41l-9 22M14 41l9 22M82 31l-9 22M82 31l9 22"/><path class="f1 sf" d="M3 63q11 11 22 0z"/><path class="f1 sf" d="M71 53q11 11 22 0z"/><circle class="f3 sf" cx="48" cy="36" r="3.2"/>'},
    "icon-fiche": {"fr": "Fiche", "en": "Sheet", "svg": '<path class="f1 sf" d="M22 10h42l10 10v66H22z"/><path class="f2 sf" d="M64 10v10h10z"/><path class="s" d="M31 34h34M31 44h26M31 54h30M31 64h22"/><path class="f3 sf" d="M52 68h14v8H52z"/><path class="s" d="M31 78h36"/>'},
    "icon-minuteur": {"fr": "Minuteur", "en": "Timer", "svg": '<rect class="f3 sf" x="41" y="3" width="14" height="10" rx="3"/><circle class="f2 sf" cx="48" cy="50" r="39"/><circle class="f1 sf" cx="48" cy="50" r="30"/><path class="s" d="M78.0 50.0L72.0 50.0"/><path class="s" d="M71.4 63.5L68.8 62.0"/><path class="s" d="M61.5 73.4L60.0 70.8"/><path class="s" d="M48.0 80.0L48.0 74.0"/><path class="s" d="M34.5 73.4L36.0 70.8"/><path class="s" d="M24.6 63.5L27.2 62.0"/><path class="s" d="M18.0 50.0L24.0 50.0"/><path class="s" d="M24.6 36.5L27.2 38.0"/><path class="s" d="M34.5 26.6L36.0 29.2"/><path class="s" d="M48.0 20.0L48.0 26.0"/><path class="s" d="M61.5 26.6L60.0 29.2"/><path class="s" d="M71.4 36.5L68.8 38.0"/><path class="s" d="M48 50L37.0 30.9"/><circle class="dot" cx="48" cy="50" r="3"/>'},
    "icon-toque": {"fr": "Toque", "en": "Chef’s hat", "svg": '<path class="f1 sf" d="M26 66C16 56 18 40 30 36C30 24 44 20 50 28C58 20 72 26 70 38C82 42 82 58 70 66Z"/><path class="f2 sf" d="M26 66h44v14a3 3 0 0 1-3 3H29a3 3 0 0 1-3-3z"/><path class="s" d="M37 68v13M48 68v13M59 68v13"/>'},
    "icon-tablier": {"fr": "Tablier", "en": "Apron", "svg": '<path class="s" d="M35 14C35 3 61 3 61 14"/><path class="f1 sf" d="M35 14h26v24l14 4v42H21V42l14-4z"/><path class="s" d="M21 44l-11 5M75 44l11 5"/><path class="s" d="M35 38h26"/><path class="f2 sf" d="M40 58h16v13a2 2 0 0 1-2 2H42a2 2 0 0 1-2-2z"/>'},
    "icon-couteau": {"fr": "Couteau", "en": "Knife", "svg": '<path class="f1 sf" d="M8 60C12 42 32 32 58 31L60 44C40 46 22 54 8 60Z"/><path class="f3 sf" d="M58 31l28-4c4 2 4 14 0 16l-26 1z"/><circle class="dot" cx="69" cy="35.5" r="1.8"/><circle class="dot" cx="79" cy="34.5" r="1.8"/><path class="s" d="M58 31l2 13"/>'},
}
art.update(EXTRA)
out = pathlib.Path(__file__).resolve().parent.parent / "js" / "art.js"
out.write_text("/* Drawings and price bands from the Copius atlas, for the site.\n"
               "   Generated by tools/extract-art.py — do not edit. */\n"
               "window.NOKIME_ART=" + json.dumps(art, ensure_ascii=False, separators=(",", ":")) + ";\n",
               encoding="utf-8")
print(f"{len(art)} drawings → {out.relative_to(out.parent.parent)} ({out.stat().st_size//1024} KB)")
